### ISSUE TITLE
heroku push

### ISSUE THREAD

**Issue by kul1** [songrit/mindapp#14]
There is an error when deploy to heroku using: $heroku push 
1. I follow the step in here https://devcenter.heroku.com/articles/getting-started-with-ruby#introduction

2. After success deployed in heroku using heroku push and heroku open is OK
3. add gem mindapp in Gemfile and follow all mindapp proceed until able to run locally
4. git add. and commit
5. heroku push ======> Will shown good responsed (for me below) but when heroku open seem to have database problem!!!

remote:        Asset precompilation completed (18.27s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
remote: 
remote: ###### WARNING:
remote:        You have not declared a Ruby version in your Gemfile.
remote:        To set your Ruby version add this line to your Gemfile:
remote:        ruby '2.0.0'
remote:        # See https://devcenter.heroku.com/articles/ruby-versions for more information.
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:        Default types for Ruby  -> console, rake, worker
remote: 
remote: -----> Compressing... done, 35.9MB
remote: -----> Launching... done, v7
remote:        https://gentle-sea-5940.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/gentle-sea-5940.git
   79e367d..6c49e82  master -> master

6. heroku open =======> Sorry something went wrong

7. heroku logs --tail below ====>

$ heroku logs --tail
2015-01-31T13:14:06.695464+00:00 heroku[api]: Enable Logplex by myemaildotCom
2015-01-31T13:14:06.695490+00:00 heroku[api]: Release v2 created by myemaildotCom
2015-01-31T13:15:39.000481+00:00 heroku[api]: Set LANG, RAILS_ENV, RACK_ENV, SECRET_KEY_BASE config vars by myemaildotCom
2015-01-31T13:15:39.000481+00:00 heroku[api]: Release v3 created by myemaildotCom
2015-01-31T13:15:39.684335+00:00 heroku[api]: Release v4 created by myemaildotCom
2015-01-31T13:15:39.684335+00:00 heroku[api]: Set DATABASE_URL config vars by myemaildotCom
2015-01-31T13:15:39.785126+00:00 heroku[api]: Attach HEROKU_POSTGRESQL_MAUVE resource by myemaildotCom
2015-01-31T13:15:39.785126+00:00 heroku[api]: Release v5 created by myemaildotCom
2015-01-31T13:15:40.263843+00:00 heroku[api]: Scale to web=1 by myemaildotCom
2015-01-31T13:15:40.320877+00:00 heroku[api]: Deploy 79e367d by myemaildotCom
2015-01-31T13:15:40.320877+00:00 heroku[api]: Release v6 created by myemaildotCom
2015-01-31T13:15:43.858225+00:00 heroku[web.1]: Starting process with command `bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}`
2015-01-31T13:15:46.035139+00:00 app[web.1]: Puma starting in single mode...
2015-01-31T13:15:46.035167+00:00 app[web.1]: * Version 2.9.1 (ruby 2.0.0-p598), codename: Team High Five
2015-01-31T13:15:46.035169+00:00 app[web.1]: * Min threads: 5, max threads: 5
2015-01-31T13:15:46.035171+00:00 app[web.1]: * Environment: production
2015-01-31T13:15:47.743160+00:00 app[web.1]: * Listening on tcp://0.0.0.0:10993
2015-01-31T13:15:47.743448+00:00 app[web.1]: Use Ctrl-C to stop
2015-01-31T13:15:48.070372+00:00 heroku[web.1]: State changed from starting to up
2015-01-31T13:16:11.334732+00:00 app[web.1]:   Rendered welcome/index.erb within layouts/application (0.6ms)
2015-01-31T13:16:11.164185+00:00 app[web.1]: Started GET "/" for 103.7.18.71 at 2015-01-31 13:16:11 +0000
2015-01-31T13:16:11.338596+00:00 heroku[router]: at=info method=GET path="/" host=gentle-sea-5940.herokuapp.com request_id=80e0deee-a9f5-40d8-a552-3ddf4945d0f8 fwd="103.7.18.71" dyno=web.1 connect=31ms service=184ms status=200 bytes=1269
2015-01-31T13:16:11.336617+00:00 app[web.1]: Completed 200 OK in 14ms (Views: 4.5ms | ActiveRecord: 0.0ms)
2015-01-31T13:16:11.322444+00:00 app[web.1]: Processing by WelcomeController#index as HTML
2015-01-31T13:16:11.757112+00:00 heroku[router]: at=info method=GET path="/assets/application-9c38d010c5f7a158e7966b7934e43f5e.css" host=gentle-sea-5940.herokuapp.com request_id=018963a8-09c9-4f66-9de8-5df88d769d1d fwd="103.7.18.71" dyno=web.1 connect=0ms service=3ms status=200 bytes=940
2015-01-31T13:16:12.570914+00:00 heroku[router]: at=info method=GET path="/assets/application-16da03a5233f3ec1a05955a4a83d2720.js" host=gentle-sea-5940.herokuapp.com request_id=aabdc586-cb0f-46e1-8505-f7aabd10aeb3 fwd="103.7.18.71" dyno=web.1 connect=1ms service=10ms status=200 bytes=116762
2015-01-31T13:16:15.019144+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=gentle-sea-5940.herokuapp.com request_id=e42653b5-cb4c-48ac-bbcb-727aec3ef1a5 fwd="103.7.18.71" dyno=web.1 connect=0ms service=1ms status=200 bytes=143
2015-01-31T14:09:59.938602+00:00 heroku[api]: Release v7 created by myemaildotCom
2015-01-31T14:09:59.938602+00:00 heroku[api]: Deploy 6c49e82 by myemaildotCom
2015-01-31T14:10:01.140273+00:00 heroku[web.1]: State changed from up to starting
2015-01-31T14:10:04.904001+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-01-31T14:10:05.887065+00:00 app[web.1]: - Gracefully stopping, waiting for requests to finish
2015-01-31T14:10:05.887132+00:00 app[web.1]: - Goodbye!
2015-01-31T14:10:07.732682+00:00 heroku[web.1]: Process exited with status 0
2015-01-31T14:10:09.916486+00:00 heroku[web.1]: Starting process with command `bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}`
2015-01-31T14:10:13.657147+00:00 app[web.1]: * Min threads: 5, max threads: 5
2015-01-31T14:10:13.657123+00:00 app[web.1]: Puma starting in single mode...
2015-01-31T14:10:13.657145+00:00 app[web.1]: * Version 2.9.1 (ruby 2.0.0-p598), codename: Team High Five
2015-01-31T14:10:13.657148+00:00 app[web.1]: * Environment: production
2015-01-31T14:10:17.076635+00:00 app[web.1]: Use Ctrl-C to stop
2015-01-31T14:10:17.076385+00:00 app[web.1]: * Listening on tcp://0.0.0.0:43668
2015-01-31T14:10:17.110843+00:00 heroku[web.1]: State changed from starting to up
2015-01-31T14:16:56.379267+00:00 app[web.1]: Started GET "/" for 103.7.18.71 at 2015-01-31 14:16:56 +0000
2015-01-31T14:16:56.533238+00:00 app[web.1]:   Rendered mindapp/index.html.haml within layouts/application (4.0ms)
2015-01-31T14:16:56.663450+00:00 app[web.1]:   Rendered mindapp/_menu_mm.haml (116.3ms)
2015-01-31T14:16:56.663779+00:00 app[web.1]: Completed 500 Internal Server Error in 150ms
2015-01-31T14:16:56.666415+00:00 app[web.1]: Summary:
2015-01-31T14:16:56.666413+00:00 app[web.1]:   No configuration could be found for a session named 'default'.
2015-01-31T14:16:56.666402+00:00 app[web.1]: 
2015-01-31T14:16:56.666408+00:00 app[web.1]: ActionView::Template::Error (
2015-01-31T14:16:56.666437+00:00 app[web.1]:   Double check your mongoid.yml to make sure under the sessions key that a configuration exists for 'default'. If you have set the configuration programatically, ensure that 'default' exists in the configuration hash.):
2015-01-31T14:16:56.666410+00:00 app[web.1]: Problem:
2015-01-31T14:16:56.513912+00:00 app[web.1]: Processing by MindappController#index as HTML
2015-01-31T14:16:56.666439+00:00 app[web.1]:     1: - process_services
2015-01-31T14:16:56.666441+00:00 app[web.1]:     2: - Mindapp::Module.all.asc(:seq).each do |m|
2015-01-31T14:16:56.663544+00:00 app[web.1]:   Rendered mindapp/_menu.haml (121.0ms)
2015-01-31T14:16:56.663600+00:00 app[web.1]:   Rendered layouts/_full.haml (127.9ms)
2015-01-31T14:16:56.666445+00:00 app[web.1]:     4:     - next unless login?
2015-01-31T14:16:56.666443+00:00 app[web.1]:     3:   - unless m.role.blank?
2015-01-31T14:16:56.666447+00:00 app[web.1]:   app/views/mindapp/_menu_mm.haml:1:in `_app_views_mindapp__menu_mm_haml__2682173267808704448_69942958401940'
2015-01-31T14:16:56.666449+00:00 app[web.1]:   app/views/mindapp/_menu.haml:10:in `_app_views_mindapp__menu_haml___2295241469987791344_69942958051000'
2015-01-31T14:16:56.666455+00:00 app[web.1]:   app/views/layouts/application.haml:4:in `_app_views_layouts_application_haml___2524561220674929166_69942957398300'
2015-01-31T14:16:56.666458+00:00 app[web.1]: 
2015-01-31T14:16:56.666451+00:00 app[web.1]:   app/views/layouts/_full.haml:10:in `_app_views_layouts__full_haml__1307558683330894037_69942957646720'
2015-01-31T14:16:56.666457+00:00 app[web.1]: 
2015-01-31T14:16:56.666418+00:00 app[web.1]:   When attempting to create the new session, Mongoid could not find a session configuration for the name: 'default'. This is necessary in order to know the host, port, and options needed to connect.
2015-01-31T14:16:56.666434+00:00 app[web.1]: Resolution:
2015-01-31T14:16:56.670729+00:00 heroku[router]: at=info method=GET path="/" host=gentle-sea-5940.herokuapp.com request_id=e62d7b1f-5ed5-4b2f-ab6b-cc2b45ee0d56 fwd="103.7.18.71" dyno=web.1 connect=2ms service=294ms status=500 bytes=1669

**Comment by kul1** [comment]
![screen shot 2558-01-31 at 9 34 21 pm](https://cloud.githubusercontent.com/assets/3953832/5988403/2ee39cbc-a991-11e4-8aa7-fced776380d3.png)

**Comment by kul1** [comment]
I try to use mongolab as it has free sandbox for development.
So far no success yet.
Here my config/mongoid.yml

development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: ruby_getting_started_development
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
      #  - localhost:27017
	 - mongodb://heroku_app33618760:9dhqc62hhu9t68ucjlph9grktr@ds039431.mongolab.com:39431/heroku_app33618760
      options:
        # Change the default write concern. (default = { w: 1 })
        # write:
        # w: 1

        # Change the default consistency model to primary, secondary.
        # 'secondary' will send reads to secondaries, 'primary' sends everything
        # to master. (default: primary)
        # read: secondary_preferred

        # How many times Moped should attempt to retry an operation after
        # failure. (default: The number of nodes in the cluster)
        # max_retries: 20

        # The time in seconds that Moped should wait before retrying an
        # operation on failure. (default: 0.25)
        # retry_interval: 0.25
  # Configure Mongoid specific options. (optional)
  options:
    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serializaion. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Protect id and type from mass assignment. (default: true)
    # protect_sensitive_fields: true

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    # raise_not_found_error: true
    raise_not_found_error: false

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Use Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false
test:
  sessions:
    default:
      database: ruby_getting_started_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

But still error as follow.

l$ git push heroku master
Counting objects: 4, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 479 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.0.0
remote: -----> Installing dependencies using 1.7.12
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Using rake 10.4.0
remote:        Using i18n 0.6.11
remote:        Using minitest 5.4.3
remote:        Using thread_safe 0.3.4
remote:        Using builder 3.2.2
remote:        Using json 1.8.1
remote:        Using erubis 2.7.0
remote:        Using rack 1.5.2
remote:        Using arel 5.0.1.20140414130214
remote:        Using mime-types 2.4.3
remote:        Using aws_cf_signer 0.1.3
remote:        Using bcrypt-ruby 3.0.1
remote:        Using bson 2.3.0
remote:        Using bson_ext 1.5.1
remote:        Using netrc 0.10.2
remote:        Using coffee-script-source 1.8.0
remote:        Using execjs 2.2.2
remote:        Using thor 0.19.1
remote:        Using connection_pool 2.1.1
remote:        Using mini_portile 0.6.2
remote:        Using sexp_processor 4.4.5
remote:        Using tilt 1.4.1
remote:        Using hashie 3.3.2
remote:        Using hike 1.2.3
remote:        Using multi_json 1.10.1
remote:        Using mindapp 0.0.8
remote:        Using optionable 0.2.0
remote:        Using origin 2.1.1
remote:        Using pdf-core 0.4.0
remote:        Using pg 0.17.1
remote:        Using ttfunk 1.4.0
remote:        Using bundler 1.7.12
remote:        Using rails_serve_static_assets 0.0.2
remote:        Using redcarpet 3.2.2
remote:        Using rails_stdout_logging 0.0.3
remote:        Using rdoc 4.1.2
remote:        Using sass 3.2.19
remote:        Using tzinfo 1.2.2
remote:        Using puma 2.9.1
remote:        Using rack-test 0.6.2
remote:        Using mail 2.6.3
remote:        Using mongo 1.3.1
remote:        Using rest-client 1.7.2
remote:        Using uglifier 2.5.3
remote:        Using nokogiri 1.6.6.2
remote:        Using ruby_parser 3.6.4
remote:        Using omniauth 1.2.2
remote:        Using haml 4.0.6
remote:        Using coffee-script 2.3.0
remote:        Using sprockets 2.12.3
remote:        Using moped 2.0.3
remote:        Using prawn 1.3.0
remote:        Using rails_12factor 0.0.3
remote:        Using activesupport 4.1.8
remote:        Using omniauth-identity 1.1.1
remote:        Using html2haml 2.0.0
remote:        Using sdoc 0.4.1
remote:        Using cloudinary 1.0.81
remote:        Using actionview 4.1.8
remote:        Using jbuilder 2.2.5
remote:        Using activemodel 4.1.8
remote:        Using actionpack 4.1.8
remote:        Using activerecord 4.1.8
remote:        Using actionmailer 4.1.8
remote:        Using mongoid 4.0.0
remote:        Using kaminari 0.16.2
remote:        Using railties 4.1.8
remote:        Using sprockets-rails 2.2.2
remote:        Using coffee-rails 4.0.1
remote:        Using haml-rails 0.7.0
remote:        Using jquery-rails 3.1.2
remote:        Using rails 4.1.8
remote:        Using sass-rails 4.0.5
remote:        Using turbolinks 2.5.2
remote:        Your bundle is complete!
remote:        Gems in the groups development and test were not installed.
remote:        It was installed into ./vendor/bundle
remote:        Bundle completed (0.93s)
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        Psych::SyntaxError: (<unknown>): found character that cannot start any token while scanning for the next token at line 13 column 1
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/config/environment.rb:40:in `load_yaml'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/config.rb:83:in `load!'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid.rb:99:in `load!'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/mongoid-4.0.0/lib/mongoid/railtie.rb:75:in `block in <class:Railtie>'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/application.rb:276:in `require_environment!'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/application.rb:389:in `block in run_tasks_blocks'
remote:        /tmp/build_f9f6ec775e5633e7f25809ba442ef513/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to gentle-sea-5940.
remote: 
To https://git.heroku.com/gentle-sea-5940.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/gentle-sea-5940.git'

**Comment by songrit** [comment]
something wrong with mongolab, please try mongohq add-on

**Comment by kul1** [comment]
I am able to get rid database error.
but now view error as shown

2015-02-01T00:48:59.591900+00:00 heroku[api]: Release v10 created by
1.0@kul.com

2015-02-01T00:48:59.591900+00:00 heroku[api]: Deploy 8a5a78d by 1.0@kul.com

2015-02-01T00:49:41.469705+00:00 heroku[web.1]: Unidling

2015-02-01T00:49:41.470139+00:00 heroku[web.1]: State changed from down to
starting

2015-02-01T00:49:46.167328+00:00 heroku[web.1]: Starting process with
command `bundle exec puma -t 5:5 -p ${PORT:-3000} -e
${RACK_ENV:-development}`

2015-02-01T00:49:48.707678+00:00 app[web.1]: Puma starting in single mode...

2015-02-01T00:49:48.707702+00:00 app[web.1]: * Version 2.9.1 (ruby
2.0.0-p598), codename: Team High Five

2015-02-01T00:49:48.707706+00:00 app[web.1]: * Environment: production

2015-02-01T00:49:48.707705+00:00 app[web.1]: * Min threads: 5, max threads:
5

2015-02-01T00:49:52.454648+00:00 app[web.1]: Use Ctrl-C to stop

2015-02-01T00:49:52.454194+00:00 app[web.1]: * Listening on tcp://
0.0.0.0:39636

2015-02-01T00:49:52.603931+00:00 heroku[web.1]: State changed from starting
to up

2015-02-01T00:49:53.682052+00:00 app[web.1]:   Rendered
mindapp/index.html.haml within layouts/application (3.8ms)

2015-02-01T00:49:53.529877+00:00 app[web.1]: Started GET "/" for
103.7.18.71 at 2015-02-01 00:49:53 +0000

2015-02-01T00:49:53.742839+00:00 app[web.1]:

2015-02-01T00:49:53.742842+00:00 app[web.1]: ActionView::Template::Error
(undefined method `match' for nil:NilClass):

2015-02-01T00:49:53.742852+00:00 app[web.1]:
app/views/mindapp/_menu.haml:10:in
`_app_views_mindapp__menu_haml___3286162958804680981_69907853173560'

2015-02-01T00:49:53.742850+00:00 app[web.1]:
app/views/mindapp/_menu_mm.haml:1:in
`_app_views_mindapp__menu_mm_haml___3433958795582065785_69907853537180'

2015-02-01T00:49:53.742853+00:00 app[web.1]:
app/views/layouts/_full.haml:10:in
`_app_views_layouts__full_haml___3404855753699082116_69907852765000'

2015-02-01T00:49:53.742847+00:00 app[web.1]:     3:   - unless m.role.blank?

2015-02-01T00:49:53.742844+00:00 app[web.1]:     1: - process_services

2015-02-01T00:49:53.742846+00:00 app[web.1]:     2: -
Mindapp::Module.all.asc(:seq).each do |m|

2015-02-01T00:49:53.742855+00:00 app[web.1]:
app/views/layouts/application.haml:4:in
`_app_views_layouts_application_haml__689108862631295491_69907852516100'

2015-02-01T00:49:53.742857+00:00 app[web.1]:

2015-02-01T00:49:53.742858+00:00 app[web.1]:

2015-02-01T00:49:53.742849+00:00 app[web.1]:     4:     - next unless login?

2015-02-01T00:49:53.743057+00:00 heroku[router]: at=info method=GET
path="/" host=gentle-sea-5940.herokuapp.com
request_id=c4aea383-c203-4a97-976b-89c1e28c1041 fwd="103.7.18.71"
dyno=web.1 connect=1ms service=219ms status=500 bytes=1669

2015-02-01T00:49:53.663448+00:00 app[web.1]: Processing by
MindappController#index as HTML

2015-02-01T00:49:53.739695+00:00 app[web.1]:   Rendered
mindapp/_menu_mm.haml (42.7ms)

2015-02-01T00:49:53.739768+00:00 app[web.1]:   Rendered mindapp/_menu.haml
(48.6ms)

2015-02-01T00:49:53.739936+00:00 app[web.1]:   Rendered layouts/_full.haml
(55.5ms)

2015-02-01T00:49:53.740156+00:00 app[web.1]: Completed 500 Internal Server
Error in 77ms

**Comment by kul1** [comment]
mongohq seem to charge 18/m
how to use for free ?

**Comment by kul1** [comment]
Worked Great Now.
